version: "3.5"

services:

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    restart: always
    volumes:
      #declare your mount volume /host/dir:/container/dir
      - /home/app/metabase-data:/metabase-data